import Head from "next/head";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import ProductsPage from "../components/ProductsPage";
import sanityClient from "../sanity/client";

export default function collection({products}) {
  return (
    <div>
      <Head>
        <title>Dawgzonline - Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mini-logo.webp" />
      </Head>
      <Navbar />
      <ProductsPage products={products}/>
      <Footer />
    </div>
  );
}

export const getStaticProps = async() => {
  
  const products = await sanityClient.fetch(` *[ _type=="product" ]{
    _id,
    description,
    discountedPrice,
    meta,
    name,
    originalPrice,
    "imageUrl" : image.asset->url
  } `);

  return {
    props : {
      products : [...products,...products,...products,...products,...products,...products,...products,...products,...products,],
    }
  }
};
