import Head from "next/head";
import MaintenancePage from "../components/MaintenancePage";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dawgzonline </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/mini-logo.webp" />
      </Head>
      <MaintenancePage />
    </div>
  );
}
